name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  commit_lint:
    runs-on: ubuntu-latest
    steps:
      # Check commit messages
      - uses: webiny/action-conventional-commits@v1.1.0

  stylua:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download stylua
        run: make stylua

      - name: Lint
        run: make stylua-check

  luals:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: leafo/gh-actions-lua@v9
        with:
          luaVersion: "5.1.5"

      - uses: leafo/gh-actions-luarocks@v4

      - name: Download nvim-test
        run: make nvim-test

      - name: LuaLS
        run: make luals-check

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        neovim_branch:
          - 'v0.9.5'
          - 'v0.10.2'
          - 'nightly'

    env:
      NVIM_TEST_VERSION: ${{ matrix.neovim_branch }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: leafo/gh-actions-lua@v9
        with:
          luaVersion: "5.1.5"

      - uses: leafo/gh-actions-luarocks@v4

      - name: Download nvim-test
        run: make nvim-test

      - name: Run Test
        run: make test
